Dev
Univesp-Computacao/portal-disciplinas pull request #7
Opened 2022-10-25 11:03 UTC by edulonde

Resumo sobre conceitos de paradigmas de programação.

2022-10-25 11:04 UTC, edulonde commented
@felipe-dmb

2022-10-30 20:57 UTC, edulonde commented
@felipe-dmb , conseguiu dar uma olhada nesse artigo?

2022-10-31 14:02 UTC, felipe-dmb commented on docs/OOP/paradigma-programacao.md
> +Um método especial é o **método construtor** de uma classe: ele fornece valores iniciais ao objeto, ou permite que tais valores sejam determinados na criação. Uma classe pode ter mais de um construto
Nem todas as linguagens dão suporte a múltiplos construtores, normalmente, a linguagem precisa permitir sobrecarga (*overloading*).

2022-10-31 14:02 UTC, felipe-dmb commented on docs/OOP/quatro-pilares.md
> +Linguagens de programação dão suporte a encapsulamento de diversas maneiras: um procedimento é um encapsulamento de um conjunto de passos para executar uma tarefa; um vetor (*array*) é o encapsulamen
- Procedimentos costuma-se usar a palavra escopo, em vez de encapsulamento. Teve alguma referência? Seria a primeira vez que vejo nesse contexto.
- Encapsulamento em arrays, também não vi. Normalmente, eles armazenam dados de forma contígua, mas isso não significa que estão encapsulado.

2022-10-31 14:02 UTC, felipe-dmb commented on docs/OOP/quatro-pilares.md
> +Permite que uma entidade assuma diferentes significados em diferentes contextos, com o propósito de se escrever códigos que sejam reutilizáveis e de fácil manutenção. A capacidade polimórfica decorre
Perfeito, aqui está colocado a ênfase na sobrescrita e herança, porém, existe também a sobrecarga (*overloading*)

2022-10-31 14:03 UTC, felipe-dmb requested changes
Tem alguns pequenos erros de digitação, e adicionei alguns comentários, a respeito de pontos específicos:

- Método construtor;
- Polimorfismo;
- Encapsulamento;

2022-11-02 20:58 UTC, edulonde commented on docs/OOP/paradigma-programacao.md
> +Um método especial é o **método construtor** de uma classe: ele fornece valores iniciais ao objeto, ou permite que tais valores sejam determinados na criação. Uma classe pode ter mais de um construto
OK, vou destacar que se refere apenas a linguagem Java.

2022-11-02 20:58 UTC, edulonde commented on docs/OOP/quatro-pilares.md
> +Permite que uma entidade assuma diferentes significados em diferentes contextos, com o propósito de se escrever códigos que sejam reutilizáveis e de fácil manutenção. A capacidade polimórfica decorre
Acho que para resumo, dá para deixar assim. Vira escrever um resumo só sobre polimorfismo, separando melhor oque é coerção, sobrecarga e sobreescrita.

2022-11-04 15:00 UTC, felipe-dmb approved these changes
Corrigi alguns erros de digitação. Pronto para merge.

2022-11-04 16:34 UTC, merged